name: checks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up OTP / Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 23.2
          elixir-version: 1.13.1
      - name: Install dependencies
        run: mix deps.get
      - name: Check formatting
        run: mix format --check-formatted --dry-run
