name: checks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up OTP / Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 23.2
          elixir-version: 1.13.1
      - name: Install dependencies
        run: mix deps.get
      - name: Check for compilation warnings
        run: mix compile --warnings-as-errors || { echo "Compilation contains warnings. Please fix them."; exit 1; }
      - name: Check formatting
        run: mix format --check-formatted --dry-run
      - name: Run credo
        run: mix credo

  test:
    runs-on: ubuntu-latest
    needs:
      - lint
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: short_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    env:
      MIX_ENV: test
      DATABASE_PORT: 5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up OTP / Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 23.2
          elixir-version: 1.13.1
      - name: Setup test database
        run: mix setup
      - name: Run tests
        run: mix test --cover
